blank_issues_enabled: true
contact_links:
  - name: Other ways to contribute
    url: https://github.com/mscape/mscape#contribute
    about: Please find other options to contribute to the community metaverse landscape
