name: Bug Report
description: File a bug report
labels: ["project"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing a new project to the metaverse landscape!
  - type: input
    id: name
    attributes:
      label: Project name
      description: Add the name of your project
    validations:
      required: true
